# PURL configuration for https://purl.brain-bican.org/taxonomy/$$TAXONOMY_ID$$
idspace: $$TAXONOMY_ID$$
base_url: /taxonomy/$$TAXONOMY_ID$$

products:
- $$TAXONOMY_ID$$.json: https://raw.githubusercontent.com/$$PROJECT_GITHUB_ORG$$/$$PROJECT_REPO$$/main/$$TAXONOMY_ID$$.json

base_redirect: https://$$PROJECT_GITHUB_ORG$$.github.io/$$PROJECT_REPO$$

entries:

# https://purl.brain-bican.org/taxonomy/$$TAXONOMY_ID$$/$$TAXONOMY_ID$$.json
- exact: /$$TAXONOMY_ID$$.json
  replacement: https://raw.githubusercontent.com/$$PROJECT_GITHUB_ORG$$/$$PROJECT_REPO$$/main/$$TAXONOMY_ID$$.json

# https://purl.brain-bican.org/taxonomy/$$TAXONOMY_ID$$/releases/2023-09-24/$$TAXONOMY_ID$$.json
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/$$PROJECT_GITHUB_ORG$$/$$PROJECT_REPO$$/v
  tests:
    - from: /releases/2023-09-24/
      to: https://raw.githubusercontent.com/$$PROJECT_GITHUB_ORG$$/$$PROJECT_REPO$$/v2023-09-24/

# This config should be the last item since it will catch all remaining paths
# https://purl.brain-bican.org/taxonomy/$$TAXONOMY_ID$$/accession_id
- regex: ^/taxonomy/$$TAXONOMY_ID$$/(.*)$
  replacement: https://$$PROJECT_GITHUB_ORG$$.github.io/$$PROJECT_REPO$$/cell_sets/$1
  tests:
  - from: /$$TAXONOMY_ID$$/$$TAXONOMY_ID$$_1
    to: https://$$PROJECT_GITHUB_ORG$$.github.io/$$PROJECT_REPO$$/cell_sets/$$TAXONOMY_ID$$_1
